export const TOP_TRACKS_LOADING = 'TOP_TRACKS_LOADING';
export const TOP_TRACKS_LOADED = 'TOP_TRACKS_LOADED';
export const ARTIST_LOADING = 'ARTIST_LOADING';
export const ARTIST_LOADED = 'ARTIST_LOADED';