export const TOP_TRACKS_LOADING = 'TOP_TRACKS_LOADING';
export const TOP_TRACKS_LOADED = 'TOP_TRACKS_LOADED';
export const TOP_TRACKS_SEARCH_LOADED = 'TOP_TRACKS_SEARCH_LOADED';
export const SET_TRACKS_CURRENT_PAGE = 'SET_TRACKS_CURRENT_PAGE';
export const ARTIST_LOADING = 'ARTIST_LOADING';
export const ARTIST_LOADED = 'ARTIST_LOADED';